export const Template = `I’m contacting you as a constituent to ask you to support Decrim Now’s campaign against the criminalisation of sex work in the UK, and to ask you to work to achieve the full decriminalisation of sex work.

The ongoing cost of living crisis means that more people, especially women and mothers, will be pushed into sex work. The partial criminalisation of sex work in the UK (excluding Northern Ireland) puts sex workers in danger. Criminalisation forces sex workers to work alone indoors, or in more isolated areas on the street, in order to avoid being fined or arrested by the police for soliciting or ‘brothel-keeping’. This puts them at increased risk of violence from clients or the police, with no one around to help keep them safe. Criminalisation of sex workers through fines or arrests push sex workers further into poverty, and prevent them from being able to exit sex work. There will be people in your constituency who are facing this situation. Please take action to protect them.

Northern Ireland and Ireland (amongst some other European countries) have implemented the ‘Nordic Model’ on sex work, which means criminalising the purchase of sex. Some UK MPs want to implement the Nordic Model in the rest of the UK. But evidence shows that sex workers are still criminalised under the Nordic Model: sex workers in Nordic Model countries continue to report receiving fines, being arrested, being evicted from their homes or deported, as a result of doing sex work. Client criminalisation puts sex workers in danger, forcing them to avoid the police, and increasing the poverty, stigma, and violence they face.

Every sex worker-led organisation in the UK is calling for the full decriminalisation of sex work. Decriminalisation would enable sex workers to work together for safety, without fearing fines, arrests or deportation. The full decriminalisation of sex work is also endorsed by organisations including Amnesty International, the World Health Organisation, the UN Working Group on Discrimination against Women and Girls, StopAIDS, and many others.

Decrim Now are holding a drop-in event in Parliament on Tuesday 5th December, 12-2pm, hosted by Nadia Whittome MP. As your constituent I urge you to attend this event in order to listen directly to sex workers about their experiences and demands. If you’re not able to attend, please email contact@decrimnow.org.uk to set up a meeting and take action to support sex workers’ rights. Thank you.`


export const Links = `More information here:
Proceed without caution: the impact of 'prostitute cautions' and convictions on Sex Workers' lives: https://prostitutescollective.net/wp-content/uploads/2023/10/Report-Proceed-Without-Caution.pdf
What do sex workers think about the French Prostitution Act?: https://sciencespo.hal.science/hal-02115877/document
Ireland: “We live within a violent system.” Structural violence against sex workers in Ireland: https://www.amnesty.org/en/documents/eur29/5156/2022/en/
Norway: The human cost of ‘crushing’ the market: Criminalization of sex work in Norway: https://www.amnesty.org/en/documents/eur36/4034/2016/en/
Criminalising the Sex Buyer: Experiences from the Nordic Region: https://www.lse.ac.uk/women-peace-security/assets/documents/2022/W922-0152-WPS-Policy-Paper-6-singles.pdf
Crime has almost doubled in the two years since new law came in: https://uglymugs.ie/wp-content/uploads/um-statement-26-mar-2019.pdf`